name: Publish GH Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🐙
        uses: actions/checkout@v3
      - name: Nix ❄️
        uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Cachix 📦
        uses: cachix/cachix-action@v10
        with:
          name: ners-ch
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build 🔧
        run: nix build
      - name: Publish 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
